export const IMPORT_FRIENDS = 'IMPORT_FRIENDS';
export const ADD_NEW_FRIEND = 'ADD_NEW_FRIEND';
export const EDIT_FRIEND = 'EDIT_FRIEND';
export const DELETE_FRIEND = 'DELETE_FRIEND';
export const ADD_BEST_FRIEND = 'ADD_BEST_FRIEND';
export const REMOVE_BEST_FRIEND = 'REMOVE_BEST_FRIEND';
export const RESET_BEST_FRIENDs = 'RESET_BEST_FRIENDS';
export const ON_INPUT_CHANGE = 'ON_INPUT_CHANGE';
